use serde::Serialize;

use super::conversation::AIConversationId;
use super::{AIAgentExchangeId, ServerOutputId};
use crate::ai::llms::LLMId;

#[derive(Clone, Default, Debug, Serialize)]
pub struct AIIdentifiers {
    /// Useful for joining to client-side telemetry.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub client_conversation_id: Option<AIConversationId>,
    /// A stable ID to relate failures for the same underlying request.
    #[serde(rename = "exchange_id", skip_serializing_if = "Option::is_none")]
    pub client_exchange_id: Option<AIAgentExchangeId>,
    /// Unique ID for this output coming from the AI API. Generated by the server. Only passed in
    /// the initial response chunk.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub server_output_id: Option<ServerOutputId>,
    /// The conversation ID included in the response chunk.
    ///
    /// Once this is set, it is never updated. That shouldn't be an issue because the conversation
    /// ID is only expected to be passed in the initial response chunk.
    ///
    /// Note that this conversation ID is server-scoped; it is _not_ related to the
    /// `AIConversationId`, which is entirely a client-side abstraction.
    ///
    /// This is mainly used for server-side logging and analytics.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub server_conversation_id: Option<String>,
    /// The ID of the model actually used to generate the output. This may differ from the requested model.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model_id: Option<LLMId>,
}
